[2024-02-04T10:07:43.925+0100] {processor.py:161} INFO - Started process (PID=56020) to work on /home/ubuntu/airflow/dags/meteo.py
[2024-02-04T10:07:43.929+0100] {processor.py:830} INFO - Processing file /home/ubuntu/airflow/dags/meteo.py for tasks to queue
[2024-02-04T10:07:43.931+0100] {logging_mixin.py:188} INFO - [2024-02-04T10:07:43.930+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/airflow/dags/meteo.py
[2024-02-04T10:07:43.945+0100] {logging_mixin.py:188} INFO - [2024-02-04T10:07:43.937+0100] {dagbag.py:348} ERROR - Failed to import: /home/ubuntu/airflow/dags/meteo.py
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/airflow/dags/meteo.py", line 4, in <module>
    from airflow.operators.spark_submit import SparkSubmitOperator
ModuleNotFoundError: No module named 'airflow.operators.spark_submit'
[2024-02-04T10:07:43.946+0100] {processor.py:842} WARNING - No viable dags retrieved from /home/ubuntu/airflow/dags/meteo.py
[2024-02-04T10:07:44.669+0100] {processor.py:183} INFO - Processing /home/ubuntu/airflow/dags/meteo.py took 0.753 seconds
