[2024-02-04T10:07:24.039+0100] {processor.py:161} INFO - Started process (PID=55999) to work on /home/ubuntu/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-04T10:07:24.046+0100] {processor.py:830} INFO - Processing file /home/ubuntu/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-02-04T10:07:24.048+0100] {logging_mixin.py:188} INFO - [2024-02-04T10:07:24.047+0100] {dagbag.py:538} INFO - Filling up the DagBag from /home/ubuntu/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-04T10:07:37.085+0100] {processor.py:840} INFO - DAG(s) 'example_local_kubernetes_executor' retrieved from /home/ubuntu/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-02-04T10:07:37.286+0100] {logging_mixin.py:188} WARNING - /home/ubuntu/.local/lib/python3.10/site-packages/airflow/serialization/serialized_objects.py:1563 DeprecationWarning: This module is deprecated. The `cncf.kubernetes` provider before version 7.4.0 uses this module - you should migrate to a newer version of `cncf.kubernetes` to get rid of this warning. If you import the module via `airflow.kubernetes` import, please use `cncf.kubernetes' provider 7.4.0+ and switch all your imports to use `apache.airflow.providers.cncf.kubernetes` to get rid of the warning.
[2024-02-04T10:07:37.391+0100] {logging_mixin.py:188} INFO - [2024-02-04T10:07:37.390+0100] {dag.py:3033} INFO - Sync 1 DAGs
[2024-02-04T10:07:37.417+0100] {logging_mixin.py:188} INFO - [2024-02-04T10:07:37.416+0100] {dag.py:3820} INFO - Setting next_dagrun for example_local_kubernetes_executor to None, run_after=None
[2024-02-04T10:07:37.475+0100] {processor.py:183} INFO - Processing /home/ubuntu/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 13.459 seconds
